characters = {
    "Luffy": {"female": False, "strawhat_pirate": True, "captain": True, "pirate": True},
    "Zoro": {"female": False, "strawhat_pirate": True, "swordsman": True, "pirate": True},
    "Sanji": {"female": False, "strawhat_pirate": True, "cook": True, "pirate": True},
    "Chopper": {"female": False, "strawhat_pirate": True, "doctor": True, "reindeer": True, "pirate": True},
    "Franky": {"female": False, "strawhat_pirate": True, "cyborg": True, "pirate": True},
    "Brook": {"female": False, "strawhat_pirate": True, "musician": True, "skeleton": True, "pirate": True, "swordsman": True},
    "Jinbei": {"female": False, "strawhat_pirate": True, "fishman": True, "pirate": True},
    "Shanks": {"female": False, "yonko": True, "red_hair": True, "pirate": True},
    "Blackbeard": {"female": False, "yonko": True, "red_hair": False, "pirate": True, "darkness devil fruit user": True},
    "King Cobra": {"female": False, "king": True},
    "Nami": {"female": True, "strawhat_pirate": True, "navigator": True, "pirate": True},
    "Robin": {"female": True, "strawhat_pirate": True, "archaeologist": True, "pirate": True},
    "Big Mom": {"female": True, "yonko": True, "pirate": True},
    "Boa Hancock": {"female": True, "pirate_empress": True, "pirate": True},
    "Alvida": {"female": True, "pirate": True, "pirate_empress": False},
    "Vivi": {"female": True, "princess": True, "alabasta": True},
    "Shirahoshi": {"female": True, "princess": True, "fishman": True},
    "Rebecca": {"female": True, "gladiator": True},
    "Reiju": {"female": True, "princess": True, "germa": True},
    "Shakky": {"female": True, "bartender": True, "retired_pirate": True},
    "Usopp": {"female": False, "strawhat_pirate": True, "sniper": True, "pirate": True},
    "Buggy": {"female": False, "pirate": True, "clown": True, "yonko": True},
    "Ace": {"female": False, "pirate": True, "fire user": True},
    "Sabo": {"female": False, "revolutionary": True, "fire user": True},
    "Smoker": {"female": False, "marine": True, "smoke devil fruit user": True},
    "Koby": {"female": False, "marine": True},
    "Kuzan": {"female": False, "marine": True, "admiral": True},
    "Doflamingo": {"female": False, "pirate": True, "warlord": True, "string_string fruit user": True},
    "Crocodile": {"female": False, "pirate": True, "warlord": True, "sand devil fruit user": True},
    "Kaido": {"female": False, "yonko": True, "pirate": True, "mythical zoan devil fruit user": True},
}
 
traits = [
    "female", "strawhat_pirate", "yonko", "captain", "swordsman", "cook", "navigator",
    "archaeologist", "doctor", "cyborg", "musician", "skeleton", "fishman",
    "red_hair", "pirate_empress", "king", "princess", "alabasta",
    "gladiator", "germa", "bartender", "retired_pirate", "pirate", "reindeer", "sniper",
    "clown", "fire user", "revolutionary", "marine", "smoke devil fruit user", "admiral", "warlord",
    "string_string fruit user", "sand devil fruit user", "mythical zoan devil fruit user", "darkness devil fruit user"
]